// Generated by CoffeeScript 1.9.3
(function() {
  var keyFor, merge, withPatient, wrap;

  merge = require('merge');

  keyFor = {
    "Observation": "subject",
    "MedicationPrescription": "patient"
  };

  withPatient = function(cfg, type, q) {
    var query;
    if (!cfg.boundToPatient || !cfg.patient || !keyFor[type]) {
      return q;
    }
    query = merge(true, q);
    query[keyFor[type]] = {
      $type: "Patient",
      _id: cfg.patient
    };
    return query;
  };

  wrap = function(cfg, search) {
    return function(params) {
      var baseUrl, error, http, query, success, type;
      baseUrl = params.baseUrl, http = params.http, type = params.type, query = params.query, success = params.success, error = params.error;
      return search(merge(true, params, {
        query: withPatient(cfg, type, query)
      }));
    };
  };

  module.exports = wrap;

}).call(this);
