// Generated by CoffeeScript 1.9.3
(function() {
  var implementXhr, mkFhir;

  mkFhir = require('../fhir');

  implementXhr = function($http) {
    return function(q) {
      var p;
      p = $http(q);
      if (q.success) {
        p.success(q.success);
      }
      if (q.error) {
        p.error(q.error);
      }
      return p;
    };
  };

  angular.module('ng-fhir', ['ng']);

  angular.module('ng-fhir').provider('$fhir', function() {
    var prov;
    return prov = {
      $get: function($http) {
        var adapter, fhir;
        adapter = {http: implementXhr($http)};
        return mkFhir(prov, adapter);
      }
    };
  });

}).call(this);
