// Generated by CoffeeScript 1.9.3
(function() {
    var mkFhir = require('../fhir');

    $ = jQuery;

    var adapter = {
        http: function(q) {
            var ret = $.Deferred();
            $.ajax({
                type: args.method,
                url: args.url,
                headers: args.headers,
                dataType: "json",
                contentType: "application/json",
                data: args.data || args.params
            }).done(function(data, status, xhr) {
                args.success && args.success(data, status, xhr.getResponseHeader);
                ret.resolve(data, status, xhr.getResponseHeader);
            }).fail(function() {
                args.error && args.error.call(null, arguments);
                ret.reject.apply(null, argumetns);
            });
            return ret;
        }
    };

    module.exports = function(config) {
      return mkFhir(config, adapter);
    };

}).call(this);
