// Generated by CoffeeScript 1.9.3
(function() {
  exports.stepBuilder = function(q) {
    return function(name, fn) {
      return function(state) {
        var d, next;
        d = q.defer();
        console.log("Step [" + name + "]: start");
        next = function(newSt) {
          state[name] = newSt;
          console.log("Step [" + name + "]: complete");
          return d.resolve(state);
        };
        fn(next, state);
        return d.promise;
      };
    };
  };

  exports.checkStep = function(q) {
    return function(name, fn) {
      return function(state) {
        var d;
        d = q.defer();
        console.log("Step [" + name + "]: check");
        fn(state, state[name]);
        d.resolve(state);
        return d.promise;
      };
    };
  };

}).call(this);
